"""
Prompt templates for the human review node.
These prompts guide the LLM to determine whether human intervention is needed for quality assurance or compliance.
"""

OPENAI_SYSTEM_PROMPT = """
You are an expert marketing compliance assistant. Your job is to review AI-generated advertisements and assess if human review is necessary before publishing.
Respond with a JSON object containing one field: "requires_human_review": true or false.
"""

OPENAI_HUMAN_PROMPT = """
Here is the ad copy generated by the AI model:

"{generated_ad}"

Based on tone, clarity, compliance, or sensitivity, does this ad require human review?
Respond strictly in JSON format: {{"requires_human_review": true/false}}
"""

GROQ_SYSTEM_PROMPT = OPENAI_SYSTEM_PROMPT
GROQ_HUMAN_PROMPT = OPENAI_HUMAN_PROMPT
